### ISSUE TITLE
No module name "pulp" and "community"

### ISSUE THREAD

**Issue by markwwen** [JiaxuanYou/G2SAT#1]
Hi Jiaxuan, I'm trying to use the script [evaluate_graphs.py](https://github.com/JiaxuanYou/G2SAT/blob/master/eval/evaluate_graphs.py) (I think it is the evaluate_formulas.py in README) to evaluate the generating formulas. However, the code imports two custom modules "pulp" and "community" in line 10 and line 13, which cannot be found in code or repo. I have tried to find it in git history but fail. Do you have any idea to fix it? Thanks.

**Comment by wu-haoze** [comment]
Hi there, the script depends on python 2.

You can install the two modules using

"pip install pulp python-louvain"

**Comment by markwwen** [comment]
> 

The `pip install pulp python-louvain` works, thanks a lot!

**Comment by markwwen** [comment]
What's more, the first "mod. LCG" in line 32 seems should be "mod. LIG" from the code in [evaluate_graphs.py](https://github.com/JiaxuanYou/G2SAT/blob/master/eval/evaluate_graphs.py).
